version: '5.0'

actions:

  study_dates:
    run: r:v2 analysis/dataset_definition/study_dates.r
    outputs:
      highly_sensitive:
        study_dates_json: output/study_dates.json


  generate_dataset_inex:
    run: >
        ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_inex.py
        --dummy-tables dummy_tables/
        --output output/dataset_inex.arrow
      # --test-data-file analysis/dataset_definition/test_dataset_definition_inex.py
    needs:
    - study_dates
    outputs:
      highly_sensitive:
        dataset_inex: output/dataset_inex.arrow


  dataset_cleaning_inex:
    run: r:v2 analysis/dataset_clean/dataset_cleaning_inex.r
    needs: 
    - generate_dataset_inex
    outputs:
      highly_sensitive:
        dataset_inex_cleaned: output/data/dataset_inex_cleaned.arrow
      moderately_sensitive:
        cleaning_outputs: output/data_descriptions/cleaning_inex-*.txt
        cleaning_inex_data_flow: output/data_descriptions/cleaning_inex-data_flow.csv
        plot_med_count_distribution: output/figures/plot_med_count_distribution.png

  
  generate_dataset_inex_meds:
    run: >
      ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition_inex_meds.py
      --dummy-tables dummy_tables/
      --output output/dataset_inex_meds.arrow
    # --test-data-file analysis/dataset_definition/test_dataset_definition_inex_meds.py
    needs:
    - study_dates
    - dataset_cleaning_inex
    outputs:
      highly_sensitive:
        dataset_inex_meds: output/dataset_inex_meds.arrow