version: '4.0'

actions:
  study_dates:
    run: r:v2 analysis/dataset_definition/study_dates.r
    outputs:
      highly_sensitive:
        study_dates_json: output/study_dates.json

  generate_dataset:
    run: >
        ehrql:v1 generate-dataset analysis/dataset_definition/dataset_definition.py
        --test-data-file analysis/dataset_definition/test_dataset_definition.py
        --output output/dataset.csv.gz
    needs:
    - study_dates
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
