###################################################################################
# This script builds analysis/config/medication_of_interest.csv and builds expanded
# medication-dmd-codelists placing them in codelists/expanded_moi_codelists/
#
# Steps:
# 1. Define medication_of_interest_list - this is hand-updated with new meds for
#    which their OpenCodelist-derived dmd codes are in codelists/
# 2. Build an expanded dmd codelist for each medication by combining the
#    OpenCodelists dmd codes with the NHS BSA BNF-dmd mapped dmd codes.
# 3. Write this to codelists/expanded_moi_codelists/{name}-dmd-expanded.csv
# 4. Write the reference csv file to analysis/config/medication_of_interest.csv
#
# Runs outside the OpenSAFELY pipeline
#
# If the underlying BNF/dm+d source files in docs/ are updated to a newer release
# first rerun build_medication_lookup_tables.r to rebuild dmd_lookup.rds from the
# new files, then rerun this script to rebuild the expanded codelists from
# the new dmd_lookup.rds
###################################################################################

# Import libraries --------------------------------------------------------------
library(here)
library(fs)
library(tidyverse)

# Create output folder -----------------------------------------------------------
dir_create(here::here("codelists", "expanded_moi_codelists"))

# Firstly define medications of interest -----------------------------------------
# codelist_path must exist in codelists/
medication_of_interest_list <- c(
  statins = "codelists/bristol-statins-dmd.csv"
)

# Build csv that contains central references of medications of interest ----------
result <- tibble(
  name = names(medication_of_interest_list),
  codelist_path = medication_of_interest_list
)

#####################################################################################
# OpenCodelists medication codelists are made using the Pseudo BNF coding framework
# The generated dmd-mapped OpenCodelists don't quite marry up with the NHS BSA dmd-
# BNF mapping for two reasons:
# 1. The OpenCodelists mapping is about 18 months older - newer codes are missing
# 2. fn_med_lookup_building.r imputes dmd-bnf mappings for when BNF codes were
#    missing.
#
# Therefore each medication will have two codelists - the OpenCodelists generated
# dmd codelist (in codelists/ as the gold standard - likely to contain the vast
# majority of used dmd codes) and an expanded dmd-codelist (in
# codelists/epanded_moi_codelists/) generated by additionally adding the dmd
# mappings from the dmd_lookup file
#####################################################################################

# Add new column for expanded_codelist_paths
result$expanded_codelist_path <- character(nrow(result))

# Load dmd_lookup ---------------------------------------------------------------
dmd_lookup <- readRDS(here::here(
  "local_processing",
  "medication_lookup_tables",
  "dmd_lookup.rds"
))

# generate the expanded codelist looping over all the medications of interest
for (i in seq_len(nrow(result))) {
  name <- result$name[i]

  # load the OpenCodelist csv file
  raw_codelist <- read_csv(
    here::here(result$codelist_path[i]),
    col_types = cols(.default = "c")
  )

  # get all the bnf substance codes in the OpenCodelist csv
  substance_codes <- raw_codelist |>
    mutate(bnf_substance_code = substr(bnf_code, 1, 9)) |>
    distinct(bnf_substance_code) |>
    pull(bnf_substance_code)

  # get all the dmd_codes that match to those BNF codes from NHS BSA dmd_lookup
  dmd_lookup_codes <- dmd_lookup |>
    filter(bnf_substance_code %in% substance_codes) |>
    pull(dmd_code)

  # union the OpenCodelists dmd codes and the NHS BSA dmd codes
  raw_codes <- unique(raw_codelist$code)
  expanded_codes <- union(raw_codes, dmd_lookup_codes)
  n_added <- length(setdiff(expanded_codes, raw_codes))

  # print values to log
  message(sprintf(
    "--- %s: %d codes in raw OpenCodelists download, %d added from dmd_lookup.rds, %d total",
    name,
    length(raw_codes),
    n_added,
    length(expanded_codes)
  ))

  # store new file path in which expanded codelist will sit
  expanded_path <- file.path(
    "codelists",
    "expanded_moi_codelists",
    paste0(name, "-dmd-expanded.csv")
  )

  # add the new filepath to the master reference csv
  result$expanded_codelist_path[i] <- expanded_path

  # make the new codelist and put it in the new file path
  tibble(code = expanded_codes) |>
    write_csv(here::here(expanded_path))
}

# Write the final master csv ----------------------------------------------------
write_csv(
  result,
  here::here("analysis", "config", "medication_of_interest.csv")
)
