###################################################################################
# This script builds analysis/config/medication_of_interest.csv and builds expanded
# medication-dmd-codelists placing them in codelists/expanded_moi_codelists/
#
# Steps:
# 1. Define medication_of_interest_list - this is hand-updated with new meds for
#    which their OpenCodelist-derived dmd codes are in codelists/
# 2. Build an expanded dmd codelist for each medication by combining the
#    OpenCodelists dmd codes with the NHS BSA BNF-dmd mapped dmd codes.
# 3. Write this to codelists/expanded_moi_codelists/{name}-dmd-expanded.csv
# 4. Write the reference csv file to analysis/config/medication_of_interest.csv
#
# Runs outside the OpenSAFELY pipeline
#
# If the underlying BNF/dm+d source files in docs/ are updated to a newer release
# first rerun build_medication_lookup_tables.r to rebuild dmd_lookup.rds from the
# new files, then rerun this script to rebuild the expanded codelists from
# the new dmd_lookup.rds
###################################################################################

# Import libraries --------------------------------------------------------------
library(here)
library(fs)
library(tidyverse)

# Create output folders -----------------------------------------------------------
dir_create(here::here("codelists", "expanded_moi_codelists"))
dir_create(here::here("local_processing", "outputs"))

# Firstly define medications of interest -----------------------------------------
# codelist_path must exist in codelists/

# Importantly BNF codes that OpenCodelists dmd-codelist are built from need to be
# human-checked to make sure they're comprehensive. Check them against the BNF
# hierarchy file in docs/ and also review the diagnostic output from this script

medication_of_interest_list <- c(
  statins = "codelists/bristol-statins-dmd.csv"
)

# Build csv that contains central references of medications of interest ----------
result <- tibble(
  name = names(medication_of_interest_list),
  codelist_path = medication_of_interest_list
)

#####################################################################################
# OpenCodelists medication codelists are made using the Pseudo BNF coding framework
# The generated dmd-mapped OpenCodelists don't quite marry up with the NHS BSA dmd-
# BNF mapping for two reasons:
# 1. The OpenCodelists mapping is about 18 months older - newer codes are missing
# 2. fn_med_lookup_building.r imputes dmd-bnf mappings for when BNF codes were
#    missing.
#
# Therefore each medication will have two codelists - the OpenCodelists generated
# dmd codelist (in codelists/ as the gold standard - likely to contain the vast
# majority of used dmd codes) and an expanded dmd-codelist (in
# codelists/expanded_moi_codelists/) generated by additionally adding the dmd
# mappings from the dmd_lookup file
#####################################################################################

# Add new column for expanded_codelist_paths
result$expanded_codelist_path <- character(nrow(result))

# Load dmd_lookup and bnf_hierarchy ----------------------------------------------
dmd_lookup <- readRDS(here::here(
  "local_processing",
  "medication_lookup_tables",
  "dmd_lookup.rds"
))
bnf_hierarchy <- readRDS(here::here(
  "local_processing",
  "medication_lookup_tables",
  "bnf_hierarchy.rds"
))

# Empty list that will be filled with BNF codes that need manual review
substance_review_flags <- list()

###################################################################################
# Loop to generate an expanded codelist for all medications of interest
#
# This loop also prints a diagnostic that:
# - Pulls all the bnf_subparagraph_codes that correspond to bnf_substance_codes
#   present within the medication OpenCodelists (using the official bnf_lookup)
# - Then prints all the bnf_substance_codes from those subparagraphs that
#   are missing from the OpenCodelist - this is to make sure none are missing - not
#   foolproof if entire subparagraphs are missing, but a good checker.
###################################################################################

for (i in seq_len(nrow(result))) {
  name <- result$name[i]

  # load the OpenCodelist csv file
  raw_codelist <- read_csv(
    here::here(result$codelist_path[i]),
    col_types = cols(.default = "c")
  )

  # get all the bnf substance codes in the OpenCodelist csv
  substance_codes <- raw_codelist |>
    mutate(bnf_substance_code = substr(bnf_code, 1, 9)) |>
    distinct(bnf_substance_code) |>
    pull(bnf_substance_code)

  # get all the dmd_codes that match to those BNF codes from NHS BSA dmd_lookup
  dmd_lookup_codes <- dmd_lookup |>
    filter(bnf_substance_code %in% substance_codes) |>
    pull(dmd_code)

  # union the OpenCodelists dmd codes and the NHS BSA dmd codes
  raw_codes <- unique(raw_codelist$code)
  expanded_codes <- union(raw_codes, dmd_lookup_codes)
  n_added <- length(setdiff(expanded_codes, raw_codes))

  # Substance-level review: any other substance codes in the same
  # subparagraph(s) as this medication, not covered by the OpenCodelist
  subparagraphs_covered <- bnf_hierarchy |>
    filter(bnf_substance_code %in% substance_codes) |>
    distinct(bnf_subparagraph_code)

  substances_needing_review <- bnf_hierarchy |>
    filter(
      bnf_subparagraph_code %in% subparagraphs_covered$bnf_subparagraph_code,
      !bnf_substance_code %in% substance_codes
    ) |>
    distinct(bnf_substance_code, bnf_substance_name, bnf_subparagraph_name)

  substance_review_flags[[name]] <- substances_needing_review |>
    mutate(name = name)

  # print values to log
  message(sprintf(
    "--- %s: %d codes in OpenCodelists download, %d added from dmd_lookup.rds, %d total",
    name,
    length(raw_codes),
    n_added,
    length(expanded_codes)
  ))
  message(sprintf(
    "--- %s: %d substance code(s) in the same subparagraph(s) not in the OpenCodelist - review these",
    name,
    nrow(substances_needing_review)
  ))

  # store new file path in which expanded codelist will sit
  expanded_path <- file.path(
    "codelists",
    "expanded_moi_codelists",
    paste0(name, "-dmd-expanded.csv")
  )

  # add the new filepath to the master reference csv
  result$expanded_codelist_path[i] <- expanded_path

  # make the new codelist and put it in the new file path
  tibble(code = expanded_codes) |>
    write_csv(here::here(expanded_path))
}

# Write the final master csv ----------------------------------------------------
write_csv(
  result,
  here::here("analysis", "config", "medication_of_interest.csv")
)

# Write the substance-level review diagnostic ------------------------------------
bind_rows(substance_review_flags) |>
  write_csv(here::here(
    "local_processing",
    "outputs",
    "moi_substance_codes_not_in_opencodelist.csv"
  ))
