---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: LINEAR_SEGMENTS
---
flowchart TD
    %% define nodes
    a1("study_dates"):::R
    a2("generate_dataset_inex"):::ehrql
    b1("openSAFELY-TPP backend"):::openSAFELY
    d1("dataset_inex.arrow"):::data
    a3("dataset_cleaning_inex"):::R
    d2("dataset_inex_cleaned.arrow"):::data
    o1("cleaning_inex-data_flow.csv, cleaning_inex-*.txt, plot_med_count_distribution.png"):::output
    a4("generate_dataset_inex_meds"):::ehrql
    b2("openSAFELY-TPP backend"):::openSAFELY
    d3("dataset_inex_meds.arrow"):::data

    %% connect nodes
    
    b1 & a1 & a2 --> d1
    d1 --> a3 --> o1 & d2
    d2 & b2 --> a4 --> d3

    %% colour scheme
    classDef openSAFELY color:#FFFFFF, fill:#212121, stroke:#212121
    classDef ehrql color:#000000, fill:#FFD600, stroke:#FFD600
    classDef R color:#FFFFFF, fill:#E65100, stroke:#E65100
    classDef data color:#FFFFFF, fill:#1565C0, stroke:#1565C0
    classDef output color:#FFFFFF, fill:#00C853, stroke:#00C853

%% to render this type into powershell terminal
%% mmdc -i docs/pipeline_diagram.mmd -o docs/pipeline_diagram.svg